version: "3.8"

services:

  configserver:
    image: hitesh791/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - hitesh791-network
      
  accounts:
    image: hitesh791/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - hitesh791-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  
  loans:
    image: hitesh791/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - hitesh791-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: hitesh791/cards:latest
    mem_limit: 700m
    ports:
      - "9001:9001"
    networks:
      - hitesh791-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
networks:
  hitesh791-network: